services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/sites:/etc/nginx/conf.d:ro
    depends_on:
      - service-1
    restart: unless-stopped

  service-1:
    image: ghcr.io/jbps-developer/service-1:latest
    container_name: service-1
    expose:
      - "3000"
    restart: unless-stopped
